server {
  listen 4321;
  root /usr/share/nginx/html;
  location /api/ {
    proxy_pass http://auth-stub:4310;
    proxy_set_header Host $host;
  }
  location / {
    try_files $uri /index.html;
  }
}
